### ISSUE TITLE
Module importing error in v0.0.8

### ISSUE THREAD

**Issue by sakamossan** [bartoszgolebiowski/zod-csv#6]
Hello. I encountered an issue when using version 0.0.8 where modules couldn't be loaded.

## Error

```ts
$ npx jest --testPathPattern validator/spreadsheet
 FAIL  src/validator/spreadsheet.test.ts
  ● Test suite failed to run

    TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (<anonymous>)

      1 | import { readFile } from 'node:fs/promises';
    > 2 | import * as zodCsv from 'zod-csv';
        | ^
      3 | import { areaSchema } from './spreadsheet';
      4 |
      5 | describe('areaSchema', () => {

      at f (node_modules/zod-csv/dist/zcsv.umd.cjs:6:1417)
      at node_modules/zod-csv/dist/zcsv.umd.cjs:6:1446
      at node_modules/zod-csv/dist/zcsv.umd.cjs:6:1640
      at W (node_modules/zod-csv/dist/zcsv.umd.cjs:6:2289)
      at $ (node_modules/zod-csv/dist/zcsv.umd.cjs:6:2421)
      at node_modules/zod-csv/dist/zcsv.umd.cjs:8:2686
      at node_modules/zod-csv/dist/zcsv.umd.cjs:8:2692
      at node_modules/zod-csv/dist/zcsv.umd.cjs:1:162
      at Object.<anonymous> (node_modules/zod-csv/dist/zcsv.umd.cjs:1:319)
      at Object.<anonymous> (src/validator/spreadsheet.test.ts:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.699 s
Ran all test suites matching /validator\/spreadsheet/i.
```

When I downgraded to version 0.0.7, the import worked without any issues. 
There might be an issue with the generated umd.cjs file.

## Environment

```console
$ node --version
v18.13.0
$ npx jest --version
29.6.2
$ npx tsc --version
Version 4.9.5
$ head ./tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "lib": ["ES2020", "DOM"],
    "noImplicitReturns": true,
    "noUnusedLocals": false,
    "baseUrl": "src",
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
$ sw_vers
ProductName:		macOS
ProductVersion:		13.5.2
BuildVersion:		22G91
```

## その他

Though seemingly unrelated, there were warnings and 429 errors during the build process of version 0.0.8.

- [0.0.8 · bartoszgolebiowski/zod-csv@94a28a3](https://github.com/bartoszgolebiowski/zod-csv/actions/runs/5912585832/job/16036143234)

**Comment by bartoszgolebiowski** [comment]
Hello, this is very strange. You are using ESModule instead of commonjs, but "imported" commonjs. 
Can you provide me a repo with a reproduction? I will try to resolve it. 
@sakamossan

**Comment by yovanoc** [comment]
nextjs and other framework takes the main entry so this is why

**Comment by sakamossan** [comment]
Apologies for the delayed response. I have prepared a minimal code example to reproduce the issue in my environment.

- [reproduce error: TypeError: Object prototype may only be an Object or null: undefined](https://gist.github.com/sakamossan/2128748b0da8e7b884413cfe8a001883)

## Environment

- `jest.config.js`
  - Configured with only `ts-jest/presets/default-esm`
  - Node executed with `--experimental-vm-modules` option
- `tsconfig`
  - generated default using `tsc --init`

## Steps to reproduce

```
$ git clone git@gist.github.com:2128748b0da8e7b884413cfe8a001883.git repro-zodcsv
$ cd repro-zodcsv/
$ npm ci
$ npm test
```

```console
$ npm test

> tryzodcsv@1.0.0 test
> node --experimental-vm-modules node_modules/.bin/jest

 FAIL  ./index.test.ts
  ● Test suite failed to run

    TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (<anonymous>)

      at f (node_modules/zod-csv/dist/zcsv.js:204:10)
      at node_modules/zod-csv/dist/zcsv.js:207:7
      at node_modules/zod-csv/dist/zcsv.js:218:7
      at ne (node_modules/zod-csv/dist/zcsv.js:239:6)
      at $ (node_modules/zod-csv/dist/zcsv.js:248:18)
      at node_modules/zod-csv/dist/zcsv.js:385:60
      at node_modules/zod-csv/dist/zcsv.js:386:3

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.577 s
Ran all test suites.
(node:99050) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

```
$ node --version
v18.13.0

```

## Location of the error

The error occurs in the following part of the code

>       at f (node_modules/zod-csv/dist/zcsv.js:204:10)

```
    return function(c, h) {
      f(c, h);
      function p() {
        this.constructor = c;
      }
      c.prototype = h === null ? Object.create(h) : (p.prototype = h.prototype, new p());
    };
```

It seems like the issue might be related to the process of adding polyfills during transpilation.

## Other issue

It seems that this issue might be encountering a similar error. a situation where the prototype, which should be null, is instead becoming undefined.

> TypeError: Class extends value undefined is not a constructor or null

- https://github.com/bartoszgolebiowski/zod-csv/issues/7

**Comment by ffilipovicc98** [comment]
I encountered the same error as described in this thread. 

@sakamossan Have you successfully integrated zod-csv into your project?

**Comment by ffilipovicc98** [comment]
Update from my side: Downgrade to v0.0.7 worked for me. So issue is still relevant for v0.0.8.

**Comment by Lonli-Lokli** [comment]
Me too, probably needs to fork & update

**Comment by bartoszgolebiowski** [comment]
@Lonli-Lokli @sakamossan @yovanoc @ffilipovicc98 
Thank you for your comments. It was a bug csv-string library.
I have updated the zod-csv@0.1.0 with Polyfil.

Feel free to update your package.json.

**Comment by bartoszgolebiowski** [comment]
I have created nodejs project and imported it via:
```
import * as zodcsv from 'zod-csv';
import {parseCSVContent} from 'zod-csv';
```
also, I have tried to use commonjs:
```
const { parseCSVContent } = require('zod-csv');
```

It seems to work as expected.
I am sorry for any difficulties wit the library.
