### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by ebdrup** [bartoszgolebiowski/zod-csv#7]
When using 0.0.8 I get this error from just importing zod-csv:

```
/Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/@nestjs/common/node_modules/tslib/tslib.js:75
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
                  ^
TypeError: Class extends value undefined is not a constructor or null
    at __extends (/Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/@nestjs/common/node_modules/tslib/tslib.js:75:19)
    at /Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/zod-csv/dist/zcsv.umd.cjs:6:1640
    at W (/Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/zod-csv/dist/zcsv.umd.cjs:6:2289)
    at $ (/Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/zod-csv/dist/zcsv.umd.cjs:6:2421)
    at /Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/zod-csv/dist/zcsv.umd.cjs:8:2686
    at /Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/zod-csv/dist/zcsv.umd.cjs:8:2692
    at /Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/zod-csv/dist/zcsv.umd.cjs:1:60
    at Object.<anonymous> (/Users/allanebdrup/Library/CloudStorage/Dropbox/marts-api/node_modules/zod-csv/dist/zcsv.umd.cjs:1:217)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
```
node v20.9.0
yarn:  v1.22.19

**Comment by bartoszgolebiowski** [comment]
@ebdrup 
Thank you for your comment. It was a bug csv-string library.
I have updated the zod-csv@0.1.0 with Polyfil.

Feel free to update your package.json.
